# Datei: docker-compose.yml
# MariaDB mit der Datenbank db1 einrichten
version: '3'
services:
  mariadb:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: geheim
      MYSQL_DATABASE: db1
    volumes:
      - ./db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
      - ./myown.cnf:/etc/mysql/conf.d/myown.cnf
